# Generated by Django 3.0.1 on 2020-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfoodlist',
            old_name='foods',
            new_name='food',
        ),
        migrations.AddField(
            model_name='dailyfoodlist',
            name='servings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
