# Generated by Django 3.0.6 on 2020-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_ingredient_recipe_userrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'M'), ('FEMALE', 'F')], max_length=10, null=True),
        ),
    ]
