# Generated by Django 3.0.6 on 2020-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200602_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
