# Generated by Django 3.0.6 on 2020-06-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20200617_1740'),
        ('restapi', '0006_auto_20200610_2344'),
    ]

    operations = [
    ]
