# Generated by Django 3.0.6 on 2020-06-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_merge_20200617_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfood',
            old_name='recipe',
            new_name='food',
        ),
    ]
